services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    privileged: false
    env_file: ../.env
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    logging:                           # Docker-Log begrenzen: höchstens 3 × 10 MB
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
