# HTTP: ACME-Challenge für Let's Encrypt, sonst Weiterleitung auf HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name domus.biber.solar;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name domus.biber.solar;

    ssl_certificate     /etc/letsencrypt/live/domus.biber.solar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domus.biber.solar/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_session_cache   shared:SSL:10m;

    add_header Strict-Transport-Security "max-age=15768000" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    server_tokens off;

    root  /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
